# Generated by Django 3.1.3 on 2020-11-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oururl',
            name='site',
            field=models.CharField(max_length=512),
        ),
    ]
