# Generated by Django 3.1.3 on 2020-11-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourSearch', '0003_auto_20201103_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oururl',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
