# Generated by Django 3.1.3 on 2020-11-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourSearch', '0004_auto_20201103_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oururl',
            name='site',
            field=models.TextField(help_text="Imput URL's here"),
        ),
    ]
