# Generated by Django 3.1.3 on 2020-11-06 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourSearch', '0007_remove_urltable_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='COUNTTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourSearch.urltable')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourSearch.wordstable')),
            ],
        ),
    ]
