# Generated by Django 3.1.3 on 2020-11-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourSearch', '0008_counttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='counttable',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
