# Generated by Django 3.1.3 on 2020-11-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourSearch', '0009_counttable_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counttable',
            old_name='url',
            new_name='idurl',
        ),
        migrations.RenameField(
            model_name='counttable',
            old_name='word',
            new_name='idword',
        ),
    ]
